name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
        with:
          cosign-release: 'v1.7.1'


      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        working-directory: ./
        run: docker build . --file Dockerfile --tag deploytest:latest
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        id: trivy-scan
        continue-on-error: true
        with:
         image-ref: deploytest:latest
         format: 'sarif'
         output: 'trivy-results.sarif'
      
      - name: Security scan on docker image
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: deploytest:latest
          args: --file=./Dockerfile 
            --severity-threshold=low
            --sarif-file-output=./docker.snyk.sarif
          sarif: false
     
      - name: Upload Trivy scan results to GitHub Security tab\
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
         sarif_file: 'trivy-results.sarif'
